.\"Modified from man(1) of FreeBSD, the NetBSD mdoc.template, and mdoc.samples.
.\"See Also:
.\"man mdoc.samples for a complete listing of options
.\"man mdoc for the short list of editing options
.\"/usr/share/misc/mdoc.template
.Dd 03/06/2013               \" DATE 
.Dt pgcwhpolygon 1      \" Program name and manual section number 
.Os *n*x
.Sh NAME                 \" Section Header - required - don't modify 
.Nm pgcwhpolygon,
.Nd Generate the WHERE clause for a general polygon
.Sh SYNOPSIS             \" Section Header - required - don't modify
.Nm
.Op Fl v             
.Op Fl i Ar filename      
.Op Fl o Ar filename      
.Op Fl b Ar boxflag      
.Op Fl c Ar maxcorners      
.Op Fl x Ar xcol      
.Op Fl y Ar ycol      
.Op Fl R Ar yesno      
.Op Fl v 
.Sh DESCRIPTION          \" Section Header - required - don't modify
The program
.Nm
Processes a shape file (.shv) into a comma-separated file (.csv), dealing with
the nested indents, "lakes" and "islands" (areas of exclusion and inclusion).
.Pp                      \" Inserts a space
A list of items with descriptions:
.Bl -tag -width -indent  \" Begins a tagged list 
.It Fl i               \" Each item preceded by .It macro
The name of the input shape (.shp) file for this run
.It Fl  o
The name of the output comma-separated file (.csv) for this run. Note that if
this file already exists, then it will be overwritten without any warning unless
.Sy -R \&No
is also specified.
.It Fl b
The output WHERE clause either should (YES - the default) or should not (NO) contain
specification of a bounding box.
.It Fl c
The maximum number of corners (vertices) supported during tis run. The default value
is 50. The maximum is 250.
.It Fl x
The XCOL specification for the input. This is the displacement, in bytes, of the
X field in the incoming data.
.It Fl y
The YCOL specification for the input. This is the displacement, in bytes, of the
Y field in the incoming data.
.It Fl R
This run will allow (value YES - the default) or not allow (value NO) overwriting of
pre-existing output files.
.It Fl t
This parameter is not for production use. It sets the trace (debug) flags for use
during this run.
.El                      \" Ends the list
.Pp
